### ISSUE TITLE
[pie chart] legend labels should have hover text

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#25]
the hover text on the pie chart segments is really nice! Can we add it to the legend labels, too?

![image](https://user-images.githubusercontent.com/9271438/40719679-2e75d3ec-640c-11e8-8c6c-67546dc1f84b.png)

**Comment by AdrianBZG** [comment]
@yochannah Looks like the tooltip display with the onHover event for the legend items is a on-development feature for Chart.js right now 😞 

I have disabled the click event on the legend items, so you can not filter with them anymore, in order to maintain consistency for issue #24 

What do you think?

**Comment by yochannah** [comment]
It should be fine to leave it without the hover and to disable click on the legend items, yup! If we have time at some later point I'd still like for the chart to be interactive but I'll discuss that on #24
