### ISSUE TITLE
when adding a filter on GO, dataset, pathway, add those columns to the view [doubts solved]

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#37]
Once a filter has been applied, make sure to select the relevant columns in im-tables. 

e.g. if I have sorted on a GO term, I'd like to have that GO term displaying in my im-table in the middle.

**Comment by AdrianBZG** [comment]
@yochannah Please remember to question about removing filters without saving the query itself, and how to do an OR instead of AND.

**Comment by AdrianBZG** [comment]
@yochannah I have already implemented this in local, and the result is that the im-table takes a looot of time to load since it needs to add all the three columns (go term + dataset + pathway name). I've been waiting for 20 minutes and is still not loaded, so in my opinion I think this is not a good approach. We can alleviate this with the "see the filters" issue, since the user will see which filters are active, so it's the 'same'... what do you think?

**Comment by yochannah** [comment]
Yikes. Is it ok with only one filter / extra view at a time?

**Comment by AdrianBZG** [comment]
@yochannah With only one is ok, the problem is that the user may filter by different 'filters' at the same time, so how to decide which one we show?

**Comment by yochannah** [comment]
@AdrianBZG we'll need to have a think... 

@rachellyne @julie-sullivan any thoughts here? It seems reasonable to cast a broad eye over the data, given that it's a data browser....  but I'm guessing "show me the first 20 rows of all genes associated with all pathways and all GO terms and all datasets... etc" is still making humanmine choke for good reason :laughing: 

Worst case is that we only show one filter at a time, but maybe there's some other way to approach this?

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne @julie-sullivan Maybe a selectable to choose which of the three views put as extra column in the im-table? Idk

**Comment by rachellyne** [comment]
I may be missing what you are doing, but why would you want to show all genes, all GO and all Pathways?  If you start with all genes, and then add filters, your dataset should only get smaller.
Do you mean you can't add additional columns unless they are there from the start?  I think that would be an impossible situation!

**Comment by rachellyne** [comment]
If you can see what you have filtered on on the left, maybe it's not necessary to add a column as well?  It will only add a column showing the value/content of the filter.

**Comment by julie-sullivan** [comment]
I agree with Rachel! Best not to add columns when adding filters. That's not typical behaviours for faceted searches. 

A separate bit of functionality we could add later is the ability to add data types like the results tables do. But it shouldn't be tied to the filters.

**Comment by AdrianBZG** [comment]
@rachellyne @julie-sullivan Yes, the problem is that showing all the columns takes a lot of time to load the table, for instance try the following in HumanMine:

![image](https://user-images.githubusercontent.com/8275330/41850609-7110a898-7885-11e8-9afc-61cec359a84f.png)

But since now the filters are being displayed to the user and he/she can remove them, I think there is no more need to add the new columns 😄 (this discussion was opened before that functionality was added)
